name: health check

on:
    schedule:
        - cron: '30 * * * *'

jobs:
    health-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: health check
              uses: jtalk/url-health-check-action@v3
              with:
                url: https://full-stack-open-pokedex-cb10.fly.dev/
                max-attemps: 3
                retry-delay: 10s
                
